"""initial_schema

Revision ID: ecda7d78a38f
Revises: 
Create Date: 2026-04-06 19:10:15.243172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecda7d78a38f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merged_from', sa.JSON(), nullable=True),
    sa.Column('name_best', sa.String(), nullable=False),
    sa.Column('phones', sa.JSON(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('emails', sa.JSON(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('messengers', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('segment', sa.String(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('review_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_status'), ['status'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('records_found', sa.Integer(), nullable=True),
    sa.Column('records_errors', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_city'), ['city'], unique=False)

    op.create_table('enriched_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phones', sa.JSON(), nullable=True),
    sa.Column('address_raw', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('emails', sa.JSON(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('messengers', sa.JSON(), nullable=True),
    sa.Column('tg_trust', sa.JSON(), nullable=True),
    sa.Column('cms', sa.String(), nullable=True),
    sa.Column('has_marquiz', sa.Boolean(), nullable=True),
    sa.Column('is_network', sa.Boolean(), nullable=True),
    sa.Column('crm_score', sa.Integer(), nullable=True),
    sa.Column('segment', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enriched_companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enriched_companies_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_enriched_companies_crm_score'), ['crm_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_enriched_companies_segment'), ['segment'], unique=False)

    op.create_table('raw_companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phones', sa.JSON(), nullable=True),
    sa.Column('address_raw', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('emails', sa.JSON(), nullable=True),
    sa.Column('geo', sa.String(), nullable=True),
    sa.Column('messengers', sa.JSON(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('merged_into', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['merged_into'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_companies_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_companies_source'), ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_companies_source'))
        batch_op.drop_index(batch_op.f('ix_raw_companies_city'))

    op.drop_table('raw_companies')
    with op.batch_alter_table('enriched_companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enriched_companies_segment'))
        batch_op.drop_index(batch_op.f('ix_enriched_companies_crm_score'))
        batch_op.drop_index(batch_op.f('ix_enriched_companies_city'))

    op.drop_table('enriched_companies')
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_city'))

    op.drop_table('pipeline_runs')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_status'))
        batch_op.drop_index(batch_op.f('ix_companies_city'))

    op.drop_table('companies')
    # ### end Alembic commands ###
